#!/bin/bash
# prints example commands (does not run packer/terraform)

echo "Golden image builder (GCP)"
echo "=========================="
echo "1) Debian 11 + Apache"
echo "2) RHEL 7 + httpd"
echo "3) RHEL 8 + httpd"
echo "4) RHEL 9 + httpd"
echo "5) CentOS 7 + httpd"
echo "6) Windows Server 2016 + IIS"
echo ""
echo "Packer:"
echo "  Debian:   cd packer/debian && packer init simple-apache.pkr.hcl && packer build simple-apache.pkr.hcl"
echo "  RHEL7:    cd packer/rhel7 && packer init httpd.pkr.hcl && packer build httpd.pkr.hcl"
echo "  RHEL8:    cd packer/rhel8 && packer init httpd.pkr.hcl && packer build httpd.pkr.hcl"
echo "  RHEL9:    cd packer/rhel9 && packer init httpd.pkr.hcl && packer build httpd.pkr.hcl"
echo "  CentOS7:  cd packer/centos7 && packer init httpd.pkr.hcl && packer build httpd.pkr.hcl"
echo "  Windows:  cd packer/windows && packer init windows-server-2016.pkr.hcl && packer build windows-server-2016.pkr.hcl"
echo ""
echo "Terraform:"
echo "  cd terraform/<debian|windows|rhel7|rhel8|rhel9|centos7> && terraform init && terraform apply"
echo "  (copy terraform.tfvars.example -> terraform.tfvars where needed)"
